Failed checking if argv[0] is an import path entry
Traceback (most recent call last):
  File "<frozen zipimport>", line 92, in __init__
KeyError: '/home/alexander/school/exeter/phd-physics/upgrade_report/case_studies/common/structures/interfaces/380_C308Si72_111_111_a0.0_b0.0_c0.0_interface5shift1/run-mace.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen zipimport>", line 94, in __init__
  File "<frozen zipimport>", line 345, in _read_directory
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/alexander/school/exeter/phd-physics/upgrade_report/case_studies/common/structures/interfaces/380_C308Si72_111_111_a0.0_b0.0_c0.0_interface5shift1/run-mace.py", line 4, in <module>
    from ase.io import read
  File "/home/alexander/lib/python3.12/site-packages/ase/__init__.py", line 8, in <module>
    import ase.parallel  # noqa
    ^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/lib/python3.12/site-packages/ase/parallel.py", line 9, in <module>
    import numpy as np
  File "/home/alexander/lib/python3.12/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/home/alexander/lib/python3.12/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/home/alexander/lib/python3.12/site-packages/numpy/core/__init__.py", line 104, in <module>
    from . import _internal
  File "/home/alexander/lib/python3.12/site-packages/numpy/core/_internal.py", line 150, in <module>
    sep_re = re.compile(r'\s*,\s*')
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/re/__init__.py", line 228, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/re/__init__.py", line 307, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/re/_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/re/_parser.py", line 979, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/re/_parser.py", line 460, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/re/_parser.py", line 689, in _parse
    if item[0][0] in _REPEATCODES:
       ~~~~^^^
  File "/home/alexander/anaconda3/lib/python3.12/re/_parser.py", line 168, in __getitem__
    def __getitem__(self, index):

KeyboardInterrupt
